### PR TITLE
add polling_minute parameter

### LINKED ISSUE #22: polling time as parameter
add a polling time as yams parameter to fetch data more often than once per hour

### PR DESCRIPTION
**Pull request by gpongelli**
to fetch data more often than once per hour.

closes #22

### CODE REVIEW

**Comment by Danielhiversen** [comment]
Why?
The data are not updating that often?

**Comment by gpongelli** [comment]
I don’t think so.
The async_call_later expects a time amount in seconds, and a fixed value of 3600 means once in an hour.

**Comment by Danielhiversen** [comment]
Why do you want to fetch data more often?

**Comment by gpongelli** [comment]
I need more fresh data to have better control on the roller shutter and being notified when it’s raining, so it’s possible to add an automation and close things.

**Comment by Danielhiversen** [comment]
The source data are hourly, so it does not make sense to fetch the data anymore often

**Pull request closed without merging**
